[workspace]
members = [
]
[package]
name = "yaml"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "yaml"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]
[dependencies]
libc= "0.2"
